config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'persons/profile'

  get 'persons/profile', as: 'user_root'

  devise_scope :user do
     get '/login', :to => "devise/sessions#new"
     get '/signup', :to => "devise/registrations#new"
     delete '/logout', :to => "devise/sessions#destroy"
     get '/admin/login', :to => "devise/sessions#new"

  end

  mount Spree::Core::Engine, :at => '/'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_and_belongs_to_many :roles
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :spree_roles,
                          :join_table => 'spree_roles_users',
                          :foreign_key => "user_id",
                          :class_name => "Spree::Role"

  has_many :spree_orders, :foreign_key => "user_id", :class_name => "Spree::Order"

  belongs_to :ship_address, :class_name => 'Spree::Address'
  belongs_to :bill_address, :class_name => 'Spree::Address'

  # has_spree_role? simply needs to return true or false whether a user has a role or not.
  def has_spree_role?(role_in_question)
     spree_roles.where(:name => role_in_question.to_s).any?
  end

  def last_incomplete_spree_order
     spree_orders.incomplete.where(:created_by_id => self.id).order('created_at DESC').first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # def after_sign_in_path_for(resource)
  #   # '/user/spree_user/sign_in'
  # end
#   after_filter :store_location

# def store_location
#   # store last url - this is needed for post-login redirect to whatever the user last visited.
#   return unless request.get? 
#   if (request.path != "/users/sign_in" &&
#       request.path != "/users/sign_up" &&
#       request.path != "/users/password/new" &&
#       request.path != "/users/password/edit" &&
#       request.path != "/users/confirmation" &&
#       request.path != "/users/sign_out" &&
#       !request.xhr?) # don't store ajax calls
#     session[:previous_url] = request.fullpath 
#   end
# end

# def after_sign_in_path_for(resource_or_scope)
    
# end


end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mans_helper.rb
module MansHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopx</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<script>document.write(document.cookie);</script>
</body>
</html>

app/views/mans/new.html.erb
<h1>Mans#new</h1>
<% if spree_current_user %>
      <li>
       <%= link_to Spree.t(:logout), spree_logout_path, :method => :delete %>
      </li>
     <% else %>
      <li>
       <%= link_to Spree.t(:login), spree_login_path %>
      </li>
      <li>
       <%= link_to Spree.t(:signup), spree_signup_path %>
      </li>
<% end %>

app/views/persons/profile.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>

<% if spree_current_user %>
  <li>
    <%= link_to Spree.t(:logout), spree_logout_path, :method => :delete %>
  </li>
<% else %>
  <li>
    <%= link_to Spree.t(:login), spree_login_path %>
  </li>
  <li>
    <%= link_to Spree.t(:signup), spree_signup_path %>
  </li>
<% end %>

app/views/spree/shared/_login_bar.html.erb
<% if spree_current_user %>
  <li>
    <%= link_to Spree.t(:logout), spree_logout_path, :method => :delete %>
  </li>
<% else %>
  <li>
    <%= link_to Spree.t(:login), spree_login_path %>
  </li>
  <li>
    <%= link_to Spree.t(:signup), spree_signup_path %>
  </li>
<% end %>